@menu
* Board Data Structures::      Board Data Structures
* Board Setup Functions::      Board Setup Functions
* Move Functions::             Move Functions
* Status Functions::           Status Functions
* String Functions::           String and Miscellaneous Functions
@end menu

The foundation of the GNU Go engine is a library of very efficient
routines for handling go boards.  This board library, called
@file{libboard}, can be used for those programs that only need a
basic go board but no AI capability. One such program is
@file{patterns/joseki.c}, which compiles joseki pattern
databases from SGF files.

The library consists of the following files:

@itemize
@item @file{board.c}
@quotation
The basic board code.  It uses incremental algorithms for keeping track
of strings and liberties on the go board.
@end quotation

@item @file{hash.c}
@quotation
Code for hashing go positions.
@end quotation

@item @file{globals.c}
@quotation
Global variables needed in the rest of the files.  This file also
contains global variables needed in the rest of the engine.
@end quotation

@item @file{sgffile.c}
@quotation
Implementation of output file in SGF format.
@end quotation

@item @file{showbord.c}
@quotation
Print go boards.
@end quotation

@item @file{printutils.c}
@quotation
Utilities for printing go boards and other things.
@end quotation

@end itemize

To use the board library, you must include @file{liberty.h} just like
when you use the whole engine, but of course you cannot use all the
functions declared in it, i.e. the functions that are part of the
engine, but not part of the board library.  You must link your
application with @code{libboard.a}.

@node Board Data Structures, Board Setup Functions, , Libboard
@section Board Data structures

The basic data structures of the board correspond tightly to the
@code{board_state} struct described in @xref{The Board State}. They are all
stored in global variables for efficiency reasons, the most important of which
are:

@example
@group

int           board_size;
Intersection  board[MAXSIZE];
int           board_ko_pos;

float         komi;
int           white_captured;
int           black_captured;

Hash_data     hashdata;
@end group
@end example

The description of the @code{Position} struct is applicable to these
variables also, so we won't duplicate it here.  All these variables are
globals for performance reasons.  Behind these variables, there are a
number of other private data structures.  These implement incremental
handling of strings, liberties and other properties 
(@pxref{Incremental Board}). The variable @code{hashdata} contains information
about the hash value for the current position (@pxref{Hashing}).

These variables should never be manipulated directly, since they are
only the front end for the incremental machinery. They can be read, but
should only be written by using the functions described in the next
section. If you write directly to them, the incremental data structures
will become out of sync with each other, and a crash is the likely
result. 

@node Board Setup Functions, Move Functions, Board Data Structures, Libboard
@section Board Functions

These functions are all the public functions in @file{engine/board.c}.

@subsection Setup Functions

These functions are used when you want to set up a new position without
actually playing out moves.

@itemize @bullet
@item @code{void clear_board()}
@findex clear_board
@quotation
Clears the internal board (@code{board[]}), resets the ko position,
captured stones and recalculates the hash value.
@end quotation

@item @code{void setup_board(Intersection new_board[MAX_BOARD][MAX_BOARD], int ko_pos, int *last, float new_komi, int w_captured, int b_captured)}
@findex setup_board
@quotation
Set up a new board position using the parameters.
@end quotation

@item @code{void add_stone(int pos, int color)}
@findex add_stone
@quotation
Place a stone on the board and update the hashdata.  No captures are
done. 
@end quotation

@item @code{void remove_stone(int pos)}
@findex remove_stone
@quotation
Remove a stone from the board and update the hashdata.
@end quotation
@end itemize

@node Move Functions, Status Functions, Board Setup Functions, Libboard
@subsection Move Functions

@strong{Reading}, often called @strong{search} in computer game
theory, is a fundamental process in GNU Go. This is the process
of generating hypothetical future boards in order to determine
the answer to some question, for example "can these stones live."
Since these are hypothetical future positions, it is important
to be able to undo them, ultimately returning to the present
board. Thus a move stack is maintained during reading. When
a move is tried, by the function @code{trymove}, or its
variant @code{tryko}. This function pushes the current board
on the stack and plays a move. The stack pointer @code{stackp},
which keeps track of the position, is incremented. The function
@code{popgo()} pops the move stack, decrementing @code{stackp} and
undoing the last move made.

Every successful @code{trymove()} must be matched with a @code{popgo()}.
Thus the correct way of using this function is:

@example
@group

  if (trymove(pos, color, ... )) @{
       ...    [potentially lots of code here]
       popgo();
  @}   

@end group
@end example

@noindent
Here the @code{komaster} is only set if a conditional ko capture has been made
at an earlier move. This feature of the tactical and owl reading code in GNU
Go is used to prevent redundant reading when there is a ko on the board
(@pxref{Ko}).

@itemize @bullet
@item @code{void play_move(int pos, int color)}
@findex play_move
@quotation
Play a move at @code{(pos)}. If you want to test for legality you
should first call @code{is_legal()}. This function strictly follows the
algorithm:
@enumerate
@item Place a stone of given color on the board.
@item If there are any adjacent opponent strings without liberties, remove
them and increase the prisoner count.
@item If the newly placed stone is part of a string without liberties,
remove it and increase the prisoner count.
@end enumerate
@end quotation

@item @code{int trymove(int pos, int color, const char *message, int str, int komaster, int kom_pos)}
@findex trymove
@quotation
Returns true if @code{(pos)} is a legal move for @code{color}. In that
case, it pushes the board on the stack and makes the move, incrementing
@code{stackp}. If the reading code is recording reading variations (as
with @option{--decide-string} or with @option{-o}), the string
@code{*message} will be inserted in the SGF file as a comment. The
comment will also refer to the string at @code{str} if this is not
@code{0}. The komaster and ko position variables are described 
elsewhere (@pxref{Ko})
@end quotation
@item @code{int TRY_MOVE()}
@findex TRY_MOVE
@quotation
Wrapper around trymove which suppresses @code{*message} and @code{(k,l)}.
Used in @file{helpers.c}
@end quotation
@item @code{int tryko(int pos, int color, const char *message, int komaster, int kom_pos)}
@findex tryko
@quotation
@code{tryko()} pushes the position onto the stack, and makes a move
@code{pos} of @code{color}. The move is allowed even if it is an
illegal ko capture. It is to be imagined that @code{color} has made an
intervening ko threat which was answered and now the continuation is to
be explored. Return 1 if the move is legal with the above
caveat. Returns zero if it is not legal because of suicide.
@end quotation

@item @code{void popgo()}
@findex popgo
@quotation
Pops the move stack. This function must (eventually) be called after a
succesful @code{trymove} or @code{tryko} to restore the board
position. It undoes all the changes done by the call to
@code{trymove/tryko} and leaves the board in the same state as it was
before the call.

@strong{NOTE}: If @code{trymove/tryko} returns @code{0}, i.e. the tried
move was not legal, you must @strong{not} call @code{popgo}.
@end quotation

@item @code{int komaster_trymove(int pos, int color, const char *message, int str, int komaster, int kom_pos, int *new_komaster, int *new_kom_pos, int *is_conditional_ko, int consider_conditional_ko)}
@findex komaster_trymove
@quotation
Variation of @code{trymove}/@code{tryko} where ko captures (both
conditional and unconditional) must follow a komaster scheme
(@pxref{Ko}).
@end quotation

@item @code{int move_in_stack(int pos, int cutoff)}
@findex move_in_stack
@quotation
Returns true if at least one move been played at @code{(pos)}
at deeper than level 'cutoff' in the reading tree.
@end quotation

@item @code{void void get_move_from_stack(int k, int *move, int *color)}
@findex get_move_from_stack
@quotation
Retrieve the move number @code{k} from the move stack.  The move
location is returned in @code{(*move)}, and the color that made the
move is returned in @code{*color}.
@end quotation

@item @code{void dump_stack(void)}
@findex dump_stack
@quotation
Handy for debugging the reading code under GDB. Prints the move stack.
Usage: @code{(gdb) set dump_stack()}.
@end quotation

@item @code{void reset_trymove_counter()}
@findex reset_trymove_counter
@quotation 
Reset the trymove counter.  This counter is incremented every time that
a variant of @code{trymove} or @code{tryko} is called.
@end quotation

@item @code{int get_trymove_counter()}
@findex get_trymove_counter
@quotation 
Retrieve the trymove counter.
@end quotation
@end itemize

@node Status Functions, String Functions, Move Functions, Libboard
@subsection Status Functions

These functions are used for inquiring about properties of the current
position or of potential moves.

@itemize @bullet
@item @code{int is_pass(int pos)}
@findex is_pass
@quotation 
Returns true if the move @code{(pos)} is PASS_MOVE, that is, 0.
@end quotation

@item @code{int is_legal(int pos, int color)}
@findex is_legal
@quotation 
Returns true if a move at @code{pos} is legal for @code{color}.
@end quotation

@item @code{int is_ko(int pos, int color, int *ko_pos)}
@findex is_ko
@quotation
Return true if the move @code{pos} by @code{color} is a ko capture
whether capture is a legal ko capture on this move or not. If
@code{*ko_pos} are non-@code{NULL}, then the location of the
captured ko stone are returned through @code{*ko_pos}. If the move
is not a ko capture, @code{*ko_pos} is set to 0.
@end quotation

@item @code{int is_illegal_ko_capture(int pos, int color)}
@findex is_illegal_ko_capture
@quotation
Return true if the move @code{POS} by @code{color} would be an illegal
ko capture.  There is no need to call both @code{is_ko} and
@code{is_illegal_ko_capture}. 
@end quotation

@item @code{int is_self_atari(int pos, int color)}
@findex is_self_atari
@quotation
Return true if a move by @code{color} at @code{pos} would be a self
atari, i.e. whether it would get only one liberty. This function returns
true also for the case of a suicide move.
@end quotation

@item @code{int is_suicide(int pos, int color)}
@findex is_suicide
@quotation 
Returns true if a move at @code{pos} is suicide for @code{color}.
@end quotation

@item @code{int does_capture_something(int pos, int color)}
@findex does_capture_something
@quotation 
Returns true if a move at @code{pos} does capture any stone for the
other side.
@end quotation

@item @code{int stones_on_board(int color)}
@findex stones_on_board
@quotation
Return the number of stones of the indicated color(s) on the board. This
only count stones in the permanent position, not stones placed by
@code{trymove()} or @code{tryko()}. Use
@code{stones_on_board(BLACK | WHITE)} to get the total number of stones
on the board.
@end quotation
@end itemize

@node String Functions, , Status Functions, Libboard
@subsection String and Miscellaneous Functions

These functions are used for getting information like liberties, member
stones and similar about strings. Most of these are here because they
have a particularly efficient implementation through access to the
incremental data structures behind the scene.

@itemize @bullet

@item @code{void find_origin(int str)}
@findex find_origin
@quotation
Find the origin of a worm or a cavity, i.e. the point with the
smallest 1D board coordinate. The idea is to have a canonical
reference point for a string (@pxref{Worms}).
@end quotation

@item @code{int findstones(int str, int maxstones, int *stones)}
@findex findstones
@quotation
Find the stones of the string at @code{str}. @code{str} must not
be empty. The locations of up to @code{maxstones} stones are written into
@code{*stone}. The full number of stones is returned.
@end quotation

@item @code{int countstones(int str)}
@findex countstones
@quotation
Count the number of stones in a string.
@end quotation
@item @code{void mark_string(int str, char mx[BOARDMAX], char mark)}
@findex mark_string
@quotation
For each stone in the string at pos, set mx to value mark. If
some of the stones in the string are marked prior to calling this
function, only the connected unmarked stones starting from pos
are guaranteed to become marked. The rest of the string may or may
not become marked. (In the current implementation, it will.)
@end quotation

@item @code{int liberty_of_string(int pos, int str)}
@findex liberty_of_string
@quotation
Returns true if @code{pos} is a liberty of the string at @code{str}.
@end quotation

@item @code{int neighbor_of_string(int pos, int str)}
@findex neighbor_of_string
@quotation
Returns true if pos is adjacent to the string at str.
@end quotation

@item @code{int same_string(int str1, int str2)}
@findex same_string
@quotation
Returns true if @code{str1} and @code{str2} belong to the same string.
@end quotation

@item @code{int findlib(int str, int maxlib, int *libs)}
int findlib
@quotation
Find the liberties of the string at str. str must not be
empty. The locations of up to maxlib liberties are written into
@code{libs[]}. The full number of liberties is returned.
If you want the locations of all liberties, whatever their number,
you should pass @code{MAXLIBS} as the value for maxlib and allocate space
for @code{libs[]} accordingly.
@end quotation

@item @code{int countlib(int str)}
@findex countlib
@quotation
Count the number of liberties of the string at @code{str}, which
must not be empty.
@end quotation

@item @code{int fastlib(int pos, int color, int ignore_capture)}
@findex fastlib
@quotation
Count the liberties a stone of the given color would get if played at
@code{pos}.  Captures are ignored based on the ignore_capture flag.  (pos)
must be empty.  It will fail if there is more than one string neighbor of the
same color.  In this case, the return value is -1.  Captures are not handled,
so if ignore_capture is 0, and a capture is required, -1 is returned. The
intent of this function is to be as fast as possible, not necessarily
complete.
@end quotation

@item @code{int approxlib(int pos, int color, int maxlib, int *libs)}
@findex approxlib
@quotation
Find the liberties a stone of the given color would get if played
at @code{pos}, ignoring possible captures of opponent stones. 
@code{pos} must be empty. If @code{libs != NULL}, the locations of up to 
@code{maxlib} liberties are written into @code{libs[]}. The counting of
liberties may or may not be halted when maxlib is reached. The
number of liberties found is returned. If you want the number or the locations
of all liberties, however many they are, you should pass @code{MAXLIBS} as the
value for @code{maxlib} and allocate space for @code{libs[]} accordingly.
@end quotation

@item @code{int count_common_libs(int str1, int str2)}
@findex count_common_libs
@quotation
Find the number of common liberties of the two strings at str1 and str2.
@end quotation

@item @code{int find_common_libs(int str1, int str2, int maxlib, int *libs)}
@findex find_common_libs
@quotation
Find the common liberties of the two strings at @code{str1} and
@code{str2}. The locations of up to maxlib common liberties are written into
@code{libs[]}.  The full number of common liberties is returned.  If you want
the locations of all common liberties, whatever their number, you should pass
@code{MAXLIBS} as the value for maxlib and allocate space for @code{libs[]}
accordingly.
@end quotation

@item @code{int have_common_lib(int str1, int str2, int *lib)}
@findex have_common_lib
@quotation
Determine whether two strings have at least one common liberty.
If they have and @code{lib != NULL}, one common liberty is returned in *lib.
@end quotation

@code{int chainlinks(int str, int adj[MAXCHAIN])}
@findex chainlinx
@quotation
Returns (in the @code{adj} array) the chains surrounding
the string at @code{str}. The number of chains is returned.
@end quotation

@code{int chainlinks2(int str, int adj[MAXCHAIN], int lib)}
@findex chainlinx
@quotation
Returns (in the @code{adj} array) the chains surrounding
the string at @code{str} having exactly @code{lib} liberties. The number of
chains is returned.  
@end quotation
@end itemize


@subsection Miscellaneous Functions

@itemize @bullet
@item @code{ incremental_order_moves(int move, int color, int str, int *number_edges, int *number_same_string, int *number_own, int *number_opponent, int *captured_stones, int *threatened_stones, int *saved_stones, int *number_open)}
@findex incremental_order_moves
@quotation
Help collect the data needed by @code{order_moves()} in @file{reading.c}.
It's the caller's responsibility to initialize the result parameters.
@end quotation
@end itemize
