\input texinfo @c -*-Texinfo-*-
@c %**start of header
@setfilename gnugo.info
@settitle GNU Go Documentation
@c %**end of header

@dircategory GNU games
@direntry
* GNU Go: (gnugo).          The GNU Go program
@end direntry

@set EDITION 3.8
@set VERSION 3.8

@finalout
@titlepage
@subtitle Documentation for the GNU Go Project
@subtitle Edition @value{EDITION}
@subtitle February, 2009
@vskip 0pt plus 1filll
@image{logo-36}
@vskip 0pt plus 1filll
@author By Arend Bayer, Daniel Bump, Evan Berggren Daniel, 
@author David Denholm, Jerome Dumonteil, Gunnar Farneb@"ack,
@author Paul Pogonyshev, Thomas Traber, Tanguy Urvoy, Inge Wallin

@sp 1
@page
@title{GNU Go 3.8}
@vskip 0pt plus 1filll
Copyright @copyright{} 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
2008 and 2009 @uref{http://www.fsf.org,Free Software Foundation}, Inc.
@sp 2

This is Edition @value{EDITION} of @cite{The GNU Go Project documentation}, @*
for the @value{VERSION} version of the GNU Go program.

@sp 2
Published by the Free Software Foundation Inc @*
51 Franklin Street, Fifth Floor @* 
Boston, MA  02110-1301 @*
USA @*
Tel: 617-542-5942 @*

Permission is granted to make and distribute verbatim
or modified copies of this manual is given provided
that the terms of the GNU Free Documentation License
(@pxref{GFDL}, version 1.3 or any later version) are respected.

Permission is granted to make and distribute verbatim
or modified copies of the program GNU Go is given provided
the terms of the GNU General Public License (@pxref{GPL},
version 3 or any later version) are respected.

@end titlepage

@contents

@node Top
@top
@ifinfo
@unnumbered GNU Go

This manual documents @code{GNU Go}, a Go program and its sources.
This is Edition @value{EDITION} of the @cite{GNU Go Program Documentation}

Copyright @copyright{} 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
2008 and 2009 @uref{http://www.fsf.org,Free Software Foundation}, Inc.
     
Permission is granted to make and distribute verbatim
or modified copies of this manual is given provided
that the terms of the GNU Free Documentation License
(@pxref{GFDL}, version 1.3 or any later version) are respected.

Permission is granted to make and distribute verbatim
or modified copies of the program GNU Go is given provided
the terms of the GNU General Public License (@pxref{GPL},
version 3 or any later version) are respected.

@end ifinfo

@menu
User's manual
* Introduction::                 What is GNU Go ?
* Installation::                 Installing GNU Go 
* User Guide::                   Using GNU Go

An introduction to the GNU Go engine
* Overview::                     Overview of the GNU Go engine
* Analyzing::                    Analyzing GNU Go's moves
* Move Generation::              How GNU Go generates moves
* Worms and Dragons::            Dragons and Worms
* Eyes::                         Eyes and half eyes
* Patterns::                     Pattern database
* Tactical Reading::             Tactical and Connection Reading
* Pattern Based Reading::        Pattern Based Reading: Owl and Combinations
* Influence::                    Influence Function
* Monte Carlo Go::               Monte Carlo GNU Go

Infrastructure and Interfaces
* Libboard::                     The basic go board library.
* SGF::                          Handling SGF trees in memory
* DFA::                          The DFA Pattern Matcher
* Utility Functions::            @file{utils.c} and @file{printutils.c}
* API::                          API to the GNU Go engine
* GTP::                          The Go Text Protocol
* Regression::                   Regression testing

Appendices
* Copying::                      Software and Documentation Licenses

Indices
* Concept Index::               Concept Index
* Functions Index::             Functions Index

@end menu

@node    Introduction
@chapter Introduction

@include introduction.texi

@node Installation
@chapter Installation

@include install.texi

@node User Guide
@chapter Using GNU Go

@include using.texi

@node  Overview
@chapter GNU Go engine overview

@include overview.texi

@node  Analyzing
@chapter Analyzing GNU Go's moves

@include analyze.texi


@node Move Generation
@chapter Move generation

@include move_generation.texi

@node Worms and Dragons
@chapter Worms and Dragons

@include dragon.texi

@node Eyes
@chapter Eyes and Half Eyes

@include eyes.texi

@node Patterns
@chapter The Pattern Code

@include patterns.texi

@node DFA
@chapter The DFA pattern matcher

@include dfa.texi

@node Tactical Reading
@chapter Tactical reading

@include reading.texi

@node Pattern Based Reading
@chapter Pattern Based Reading

@include owl.texi

@node Influence
@chapter Influence Function

@include influence.texi

@node Monte Carlo Go
@chapter Monte Carlo Go
@include montecarlo.texi

@node Libboard
@chapter The Board Library

@include board.texi

@node SGF
@chapter Handling SGF trees in memory

@include sgf.texi

@node API
@chapter Application Programmers Interface to GNU Go

@include api.texi

@node Utility Functions
@chapter Utility Functions

@include utils.texi

@node GTP
@chapter The Go Text Protocol

@include gtp.texi

@node Regression
@chapter Regression testing

@include regression.texi

@node Copying
@appendix Copying

@include copying.texi

@c ------------------------
@c *  END OF THE DOCUMENT *
@c ------------------------


@node  Concept Index
@unnumbered Concept Index

@printindex cp

@node  Functions Index
@unnumbered Functions Index

@printindex fn

@bye
